// This file was autogenerated by ../closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../SparkleMotion/src/animation.js', ['sm.Animation'], ['sm.Keyframe']);
goog.addDependency('../../../SparkleMotion/src/exports.js', ['SM'], ['sm', 'sm.Sequence', 'sm.TimingFunction']);
goog.addDependency('../../../SparkleMotion/src/keyframe.js', ['sm.Keyframe'], ['sm.KeyframeAttribute']);
goog.addDependency('../../../SparkleMotion/src/keyframeattribute.js', ['sm.KeyframeAttribute'], ['sm.TimingFunction']);
goog.addDependency('../../../SparkleMotion/src/runtime/cssruntime.js', ['sm.runtime.CssRuntime'], ['goog.array', 'goog.cssom', 'goog.object', 'sm.Scope', 'sm.Timeline', 'sm.TimingFunction', 'sm.runtime.Runtime']);
goog.addDependency('../../../SparkleMotion/src/runtime/javascriptruntime.js', ['sm.runtime.JavascriptRuntime'], ['goog.array', 'goog.string', 'sm.Scope', 'sm.Timeline', 'sm.TimingFunction', 'sm.runtime.Runtime']);
goog.addDependency('../../../SparkleMotion/src/runtime/playbackstate.js', ['sm.runtime.PlaybackState'], ['goog.asserts']);
goog.addDependency('../../../SparkleMotion/src/runtime/runtime.js', ['sm.runtime.Runtime'], ['goog.array', 'goog.string', 'sm.Scope', 'sm.Timeline', 'sm.TimingFunction', 'sm.runtime.NumericTween', 'sm.runtime.PlaybackState', 'sm.runtime.Timer', 'sm.runtime.Tween', 'sm.runtime.UserAgent']);
goog.addDependency('../../../SparkleMotion/src/runtime/timer.js', ['sm.runtime.Timer'], ['sm.runtime.UserAgent']);
goog.addDependency('../../../SparkleMotion/src/runtime/tween.js', ['sm.runtime.NumericTween', 'sm.runtime.Tween'], ['goog.asserts']);
goog.addDependency('../../../SparkleMotion/src/runtime/useragent.js', ['sm.runtime.UserAgent'], ['goog.userAgent']);
goog.addDependency('../../../SparkleMotion/src/scope.js', ['sm.Scope'], ['goog.object']);
goog.addDependency('../../../SparkleMotion/src/sequence.js', ['sm.Sequence'], ['sm.Scope', 'sm.Timeline', 'sm.runtime.Runtime']);
goog.addDependency('../../../SparkleMotion/src/sm.js', ['sm'], ['sm.Scope', 'sm.Sequence', 'sm.Timeline', 'sm.runtime.Runtime']);
goog.addDependency('../../../SparkleMotion/src/timeline.js', ['sm.Timeline'], ['sm.Animation']);
goog.addDependency('../../../SparkleMotion/src/timingfunction.js', ['sm.TimingFunction'], []);
goog.addDependency('../../../SparkleMotion/src/ui/editor.js', ['sm.ui.Editor'], []);
